### ISSUE TITLE
onBlockFromTo.lambda nullPointerException

### ISSUE THREAD

**Issue by codeblue1337** [PeachesMLG/EpicSkyblock#11]
[14:05:16 WARN]: [EpicSkyblock] Task #382 for EpicSkyblock v2.0.5 generated an exception
java.lang.NullPointerException: null
        at com.peaches.epicskyblock.listeners.onBlockFromTo.lambda$onBlockFromTo$0(onBlockFromTo.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-641]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-641]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[14:05:16 WARN]: [EpicSkyblock] Task #383 for EpicSkyblock v2.0.5 generated an exception
java.lang.NullPointerException: null
        at com.peaches.epicskyblock.listeners.onBlockFromTo.lambda$onBlockFromTo$0(onBlockFromTo.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-641]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-641]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by PeachesMLG** [comment]
Sorry, This was fixed a while ago. if your still having issues delete your oregen.yml
