### ISSUE TITLE
clickevent bug

### ISSUE THREAD

**Issue by ProDash1998** [PeachesMLG/EpicSkyblock#22]
**[16:10:08 INFO]: ProDash issued server command: /is upgrade
[16:10:29 ERROR]: Could not pass event InventoryClickEvent to EpicSkyblock v2.0.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[spigot.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[spigot.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[spigot.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[spigot.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[spigot.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[spigot.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at com.peaches.epicskyblock.gui.UpgradeGUI.onInventoryClick(UpgradeGUI.java:95) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor391.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[spigot.jar:git-Paper-1618]
        ... 15 more
[16:10:32 INFO]: ProDash issued server command: /gm 1**

lastes 1.12.2 paperspigot

**Comment by Jowcey** [comment]
@PeachesMLG just took a quick look at the source code, your error is that the event was triggered before "addContent" was run inside of UpgradeGUI, correct me if i'm wrong but you could fix this by adding "addContent" to the main constructor for UpgradeGUI

**Comment by PeachesMLG** [comment]
`scheduler = Bukkit.getScheduler().scheduleAsyncRepeatingTask(EpicSkyblock.getInstance(), this::addContent, 0, 10);` means it gets thrown instantly which is what the first 0 does. then after that every 0.5 seconds. This is actually caused when the player doesnt click on an item e.g. clicks outside the inventory.
