### ISSUE TITLE
Exception while executing task 57062

### ISSUE THREAD

**Issue by codeblue1337** [PeachesMLG/EpicSkyblock#6]
[18:25:16 WARN]: [EpicSkyblock] Plugin EpicSkyblock v2.0.3 generated an exception while executing task 57062
java.lang.IllegalStateException: Asynchronous player tracker update!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:359) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:523) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.EntityTracker.a(EntityTracker.java:211) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.EntityPlayer.C(EntityPlayer.java:1443) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.EntityPlayer.updateAbilities(EntityPlayer.java:1305) ~[patched_1.13.2.jar:git-Paper-638]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.setAllowFlight(CraftPlayer.java:1574) ~[patched_1.13.2.jar:git-Paper-638]
        at com.peaches.epicskyblock.Island.lambda$init$0(Island.java:277) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-638]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-638]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-638]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by PeachesMLG** [comment]
Same issue as https://github.com/PeachesMLG/EpicSkyblock/issues/5
